vlog -work work C:/Users/João Antônio/Desktop/AOC2-main/MIC1/simulation/modelsim/CPU_bipush_iadd.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.CPU_vlg_vec_tst
onerror {resume}
add wave {CPU_vlg_vec_tst/i1/CLOCK}
add wave {CPU_vlg_vec_tst/i1/LOADN}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[7]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[6]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[5]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[4]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[3]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[2]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[1]}
add wave {CPU_vlg_vec_tst/i1/MBR_OUT[0]}
add wave {CPU_vlg_vec_tst/i1/PC}
add wave {CPU_vlg_vec_tst/i1/PC[31]}
add wave {CPU_vlg_vec_tst/i1/PC[30]}
add wave {CPU_vlg_vec_tst/i1/PC[29]}
add wave {CPU_vlg_vec_tst/i1/PC[28]}
add wave {CPU_vlg_vec_tst/i1/PC[27]}
add wave {CPU_vlg_vec_tst/i1/PC[26]}
add wave {CPU_vlg_vec_tst/i1/PC[25]}
add wave {CPU_vlg_vec_tst/i1/PC[24]}
add wave {CPU_vlg_vec_tst/i1/PC[23]}
add wave {CPU_vlg_vec_tst/i1/PC[22]}
add wave {CPU_vlg_vec_tst/i1/PC[21]}
add wave {CPU_vlg_vec_tst/i1/PC[20]}
add wave {CPU_vlg_vec_tst/i1/PC[19]}
add wave {CPU_vlg_vec_tst/i1/PC[18]}
add wave {CPU_vlg_vec_tst/i1/PC[17]}
add wave {CPU_vlg_vec_tst/i1/PC[16]}
add wave {CPU_vlg_vec_tst/i1/PC[15]}
add wave {CPU_vlg_vec_tst/i1/PC[14]}
add wave {CPU_vlg_vec_tst/i1/PC[13]}
add wave {CPU_vlg_vec_tst/i1/PC[12]}
add wave {CPU_vlg_vec_tst/i1/PC[11]}
add wave {CPU_vlg_vec_tst/i1/PC[10]}
add wave {CPU_vlg_vec_tst/i1/PC[9]}
add wave {CPU_vlg_vec_tst/i1/PC[8]}
add wave {CPU_vlg_vec_tst/i1/PC[7]}
add wave {CPU_vlg_vec_tst/i1/PC[6]}
add wave {CPU_vlg_vec_tst/i1/PC[5]}
add wave {CPU_vlg_vec_tst/i1/PC[4]}
add wave {CPU_vlg_vec_tst/i1/PC[3]}
add wave {CPU_vlg_vec_tst/i1/PC[2]}
add wave {CPU_vlg_vec_tst/i1/PC[1]}
add wave {CPU_vlg_vec_tst/i1/PC[0]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[31]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[30]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[29]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[28]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[27]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[26]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[25]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[24]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[23]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[22]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[21]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[20]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[19]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[18]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[17]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[16]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[15]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[14]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[13]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[12]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[11]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[10]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[9]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[8]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[7]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[6]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[5]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[4]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[3]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[2]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[1]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_ADDR[0]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[31]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[30]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[29]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[28]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[27]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[26]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[25]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[24]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[23]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[22]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[21]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[20]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[19]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[18]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[17]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[16]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[15]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[14]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[13]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[12]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[11]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[10]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[9]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[8]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[7]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[6]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[5]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[4]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[3]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[2]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[1]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_IN[0]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[31]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[30]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[29]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[28]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[27]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[26]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[25]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[24]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[23]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[22]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[21]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[20]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[19]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[18]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[17]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[16]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[15]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[14]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[13]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[12]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[11]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[10]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[9]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[8]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[7]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[6]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[5]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[4]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[3]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[2]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[1]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_OUT[0]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[7]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[6]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[5]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[4]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[3]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[2]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[1]}
add wave {CPU_vlg_vec_tst/i1/PROG_MEM_IN[0]}
add wave {CPU_vlg_vec_tst/i1/MIR}
add wave {CPU_vlg_vec_tst/i1/MIR[35]}
add wave {CPU_vlg_vec_tst/i1/MIR[34]}
add wave {CPU_vlg_vec_tst/i1/MIR[33]}
add wave {CPU_vlg_vec_tst/i1/MIR[32]}
add wave {CPU_vlg_vec_tst/i1/MIR[31]}
add wave {CPU_vlg_vec_tst/i1/MIR[30]}
add wave {CPU_vlg_vec_tst/i1/MIR[29]}
add wave {CPU_vlg_vec_tst/i1/MIR[28]}
add wave {CPU_vlg_vec_tst/i1/MIR[27]}
add wave {CPU_vlg_vec_tst/i1/MIR[26]}
add wave {CPU_vlg_vec_tst/i1/MIR[25]}
add wave {CPU_vlg_vec_tst/i1/MIR[24]}
add wave {CPU_vlg_vec_tst/i1/MIR[23]}
add wave {CPU_vlg_vec_tst/i1/MIR[22]}
add wave {CPU_vlg_vec_tst/i1/MIR[21]}
add wave {CPU_vlg_vec_tst/i1/MIR[20]}
add wave {CPU_vlg_vec_tst/i1/MIR[19]}
add wave {CPU_vlg_vec_tst/i1/MIR[18]}
add wave {CPU_vlg_vec_tst/i1/MIR[17]}
add wave {CPU_vlg_vec_tst/i1/MIR[16]}
add wave {CPU_vlg_vec_tst/i1/MIR[15]}
add wave {CPU_vlg_vec_tst/i1/MIR[14]}
add wave {CPU_vlg_vec_tst/i1/MIR[13]}
add wave {CPU_vlg_vec_tst/i1/MIR[12]}
add wave {CPU_vlg_vec_tst/i1/MIR[11]}
add wave {CPU_vlg_vec_tst/i1/MIR[10]}
add wave {CPU_vlg_vec_tst/i1/MIR[9]}
add wave {CPU_vlg_vec_tst/i1/MIR[8]}
add wave {CPU_vlg_vec_tst/i1/MIR[7]}
add wave {CPU_vlg_vec_tst/i1/MIR[6]}
add wave {CPU_vlg_vec_tst/i1/MIR[5]}
add wave {CPU_vlg_vec_tst/i1/MIR[4]}
add wave {CPU_vlg_vec_tst/i1/MIR[3]}
add wave {CPU_vlg_vec_tst/i1/MIR[2]}
add wave {CPU_vlg_vec_tst/i1/MIR[1]}
add wave {CPU_vlg_vec_tst/i1/MIR[0]}
add wave {CPU_vlg_vec_tst/i1/MPC}
add wave {CPU_vlg_vec_tst/i1/MPC[8]}
add wave {CPU_vlg_vec_tst/i1/MPC[7]}
add wave {CPU_vlg_vec_tst/i1/MPC[6]}
add wave {CPU_vlg_vec_tst/i1/MPC[5]}
add wave {CPU_vlg_vec_tst/i1/MPC[4]}
add wave {CPU_vlg_vec_tst/i1/MPC[3]}
add wave {CPU_vlg_vec_tst/i1/MPC[2]}
add wave {CPU_vlg_vec_tst/i1/MPC[1]}
add wave {CPU_vlg_vec_tst/i1/MPC[0]}
add wave {CPU_vlg_vec_tst/i1/DATA_MEM_write_enable}
run -all
